### ISSUE TITLE
can't open file 'main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ARU25** [QKaiser/cottontail#25]
It seems that readme has not been updated for using this application.
When trying to execute `python main.py http://localhost:15672/ --username guest --password guest`
 I get this error `python: can't open file 'main.py': [Errno 2] No such file or directory`

Any instructions on how to get this tool working?

**Comment by qkaiser** [comment]
Thanks for pointing this out :) I updated the README with the instructions below.

To install it, just clone the repo and use setup.py (might need sudo rights to install system-wide):

```
git clone https://github.com/QKaiser/cottontail.git
cd cottontail
python setup.py install
```

Once installed you can call it like this:

```
cottontail http://localhost:15672/ --username guest --password guest
```
