### ISSUE TITLE
'cottontail' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by tonyprasanna** [QKaiser/cottontail#26]
cottontail is not recoginzed as a command. 
Running cottontail from this path . cottontail-master\bin\cottontail. but in your readme file you are running setup.py inside cottontail folder . 
i see setup.py is only in main folder and not inside cottontail folder.

**Comment by tonyprasanna** [comment]
Even after making explicitly placing file extension "cottontail.py"
C:\Users\Desktop\cottontail\cottontail-master_new\cottontail-master\bin>cottontail.py http://localhost:15672/ --username guest --password guest
Traceback (most recent call last):
  File "C:\Users\Desktop\cottontail\cottontail-master_new\cottontail-master\bin\cottontail.py", line 26, in <module>
    from cottontail.rabbitmq_management import *
  File "C:\Users\Desktop\cottontail\cottontail-master_new\cottontail-master\bin\cottontail.py", line 26, in <module>
    from cottontail.rabbitmq_management import *
**ImportError: No module named rabbitmq_management**

**Comment by qkaiser** [comment]
Hi !

Cottontail is not supposed to be used directly from the repository, it is provided as a Python package that you can install yourself using `setup.py`.

From within the repository, execute this command to install cottontail system-wide:

```
python setup.py install
```

**Note:** I never tested it with Windows OS, I'll look into it for Windows 7 to Windows 10. Will keep you posted.

**Comment by qkaiser** [comment]
So I checked on Windows 7 and Windows 10 and created installation instructions for Windows users. They're copied below, let me know if that works for you :)

You'll need git and python3 to install cottontail. The easiest way is to install them using [Chocolatey](https://chocolatey.org/).

```
PS C:\Users> choco install git.install
PS C:\Users> choco install python3
```

To install it, just clone the repo and use setup.py (might need administrator privileges to install system-wide):

```
PS C:\Users> git clone https://github.com/QKaiser/cottontail.git
PS C:\Users> cd cottontail
PS C:\Users\cottontail> python setup.py install
```

Once installed you can call it like this:

```
PS C:\Users> python C:\Python37\Scripts\cottontail -h

       /\ /|
       \ V/
       | "")     Cottontail v0.8.0
       /  |      Quentin Kaiser (kaiserquentin@gmail.com)
      /  \\
    *(__\_\)

usage: cottontail [-h] [--username USERNAME] [--password PASSWORD] [-v] url
cottontail: error: the following arguments are required: url
```

**Comment by tonyprasanna** [comment]
hi Kaiser ,


Regards
Prasanna KV
*"Sharing Is Caring"*

**Comment by tonyprasanna** [comment]
Hi Kaiser ,
Thank you very much for your support. Now i am able to run the tool but
still some errors after running tool .

C:\Users\Desktop\cottontail\cottontail-master\cottontail-master>python
C:\Python27\Scripts\cottontail --username admin --password admin -v
https://rabbitmq-server.xx.xx:15671/

       /\ /|
       \ V/
       | "")     Cottontail v0.8.0
       /  |      Quentin Kaiser (kaiserquentin@gmail.com)
      /  \\
    *(__\_\)

Traceback (most recent call last):
  File "C:\Python27\Scripts\cottontail", line 4, in <module>
    __import__('pkg_resources').run_script('cottontail==0.8.0',
'cottontail')
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 517, in
run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 1436, in
run_script
    exec(code, namespace, namespace)
  File
"c:\python27\lib\site-packages\cottontail-0.8.0-py2.7.egg\EGG-INFO\scripts\cottontail",
line 308, in <module>
    overview = rbmq.get_overview()
  File
"C:\Python27\lib\site-packages\cottontail-0.8.0-py2.7.egg\cottontail\rabbitmq_management.py",
line 128, in get_overview
    return self.get_request("overview")
  File
"C:\Python27\lib\site-packages\cottontail-0.8.0-py2.7.egg\cottontail\rabbitmq_management.py",
line 76, in get_request
    timeout=5
  File "C:\Python27\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 533, in
request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 646, in
send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 514, in
send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.112.158',
port=15671): Max retries exceeded with url: /api/overview (Caused by
SSLError(SSLError('_ssl.c:565: The handshake operation timed out',),))




Regards
Prasanna KV
*"Sharing Is Caring"*

**Comment by qkaiser** [comment]
Looks like cottontail cannot reach the rabbitmq HTTPS management interface that you provided. Can you try accessing it with a regular browser to see if it works ? Looks like your target is https://192.168.112.158:15671

**Comment by tonyprasanna** [comment]
Yeah . i am able to access from the Browser but from cottontail unable to
connect . we have generated separate rabbitmq Certificate and  installed
does this have any impact ?
Regards
Prasanna KV
*"Sharing Is Caring"*

**Comment by qkaiser** [comment]
> we have generated separate rabbitmq Certificate and installed does this have any impact ?

This should not be a problem given that certificate validation is explicitly disabled for all calls to the API.

This error in your stacktrace makes me think it might not be HTTPS but simply HTTP, given the SSL handshake timed out.

```
Max retries exceeded with url: /api/overview (Caused by
SSLError(SSLError('_ssl.c:565: The handshake operation timed out',),))
```

Can you double check that service on 15671 is indeed HTTPS ? Taking a network trace with wireshark might help too.

**Comment by qkaiser** [comment]
I'm closing this issue given that the initial issue has been fixed. Please open a new one if you still have connectivity issues.
