### ISSUE TITLE
Password Cracking

### ISSUE THREAD

**Issue by 3lpsy** [QKaiser/cottontail#27]
What's up with the "crack" method?

**Comment by qkaiser** [comment]
Hi,

As mentioned in the function doc, RabbitMQ web API exposes an endpoint to retrieve RabbitMQ users data:

```
curl -s -k -u redacted:redacted https://localhost:15671/api/users | json_pp
[
 {
      "hashing_algorithm" : "rabbit_password_hashing_sha256",
      "name" : "guest",
      "password_hash" : "nkDSB83UiLf8J5bDWm4HgVcaQ/Jy24glAJ68LkFltXy2l47O",
      "tags" : "administrator"
   }
]
```

I initially wrote the `crack` function to document how RabbitMQ hashes are generated and implement a check for default password in the future (e.g. dump all users, check all passwords for most used values like 'guest' or 'rabbit').

If you want to perform proper cracking, I recommend you to use hashcat with mode `20 - MD5($salt.$pass)`,  `1420 -  SHA256($salt.$pass)`, or `1720 -  SHA512($salt.$pass)` depending on the password_hash value. Note that you'll have to convert the value to its proper hashcat representation.

Let me know if it answers your question :)

**Comment by denandz** [comment]
This issues comes up pretty high in the google results when searching for RabbitMQ password cracking. If you're using hashcat, you'll want to process the hash and run hashcat like this (for sha256):

```
echo <base64 rabbit mq hash> | base64 -d | xxd -pr -c128 | perl -pe 's/^(.{8})(.*)/$2:$1/' > hash.txt
hashcat -m 1420 --hex-salt hash.txt wordlist
```
